### ISSUE TITLE
有人碰到getaddrinfo连接失败吗

### ISSUE THREAD

**Issue by Marin9527** [JaniceWuo/MovieRecommend#14]
一推荐就报错 11001

**Comment by 3492796308** [comment]
> 一推荐就报错 11001

对啊，你解决了吗

**Comment by Marin9527** [comment]
> > 一推荐就报错11001
> 
> 对啊，你解决了吗

解决了这个系统不行 缺乏数据 不会改

**Comment by 3492796308** [comment]
> > > 一推荐就报错11001
> > 
> > 
> > 对啊，你解决了吗
> 
> 解决了这个系统不行 缺乏数据 不会改



> > > 一推荐就报错11001
> > 
> > 
> > 对啊，你解决了吗
> 
> 解决了这个系统不行 缺乏数据 不会改

你怎么解决的啊

**Comment by Marin9527** [comment]
> > > > 一推荐就报错11001
> > > 
> > > 
> > > 对啊，你解决了吗
> > 
> > 
> > 解决了这个系统不行缺乏数据不会改
> 
> > > > 一推荐就报错11001
> > > 
> > > 
> > > 对啊，你解决了吗
> > 
> > 
> > 解决了这个系统不行缺乏数据不会改
> 
> 你怎么解决的啊


+我q616528863

**Comment by 3492796308** [comment]
> > > > > 一推荐就报错11001
> > > > 
> > > > 
> > > > 对啊，你解决了吗
> > > 
> > > 
> > > 解决了这个系统不行缺乏数据不会改
> > 
> > 
> > > > > 一推荐就报错11001
> > > > 
> > > > 
> > > > 对啊，你解决了吗
> > > 
> > > 
> > > 解决了这个系统不行缺乏数据不会改
> > 
> > 
> > 你怎么解决的啊
> 
> +我q616528863

电影推荐系统的加上面的qq，大家交流学习
