### ISSUE TITLE
项目运行起来了

### ISSUE THREAD

**Issue by AndyCzz** [JaniceWuo/MovieRecommend#18]
主要还是代码上的逻辑错误，有问题可以加QQ2316859570。我找别人在这个基础上二次开发的，我花了一点钱，所以有偿分享。如果你很急并且愿意花300元，ok，这个项目正好可以满足你的需求。

**Comment by lihao5201314** [comment]
你好，我加你了，一直没同意，想请教一下问题。

**Comment by lihao5201314** [comment]
> 主要还是代码上的逻辑错误，有问题可以加QQ2316859570

你好，我加你了，一直没同意，想请教一下问题。

**Comment by AndyCzz** [comment]
我现在应该同意了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lihao5201314"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午2:10
收件人:&nbsp;"JaniceWuo/MovieRecommend"<MovieRecommend@noreply.github.com&gt;;
抄送:&nbsp;"ॱଳ͘"<1296870104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JaniceWuo/MovieRecommend] 项目运行起来了 (#18)





  
主要还是代码上的逻辑错误，有问题可以加QQ2316859570
  
你好，我加你了，一直没同意，想请教一下问题。

**Comment by 3492796308** [comment]
> 主要还是代码上的逻辑错误，有问题可以加QQ2316859570

加了，同意一下吧

**Comment by AndyCzz** [comment]
> > 主要还是代码上的逻辑错误，有问题可以加QQ2316859570
> 
> 你好，我加你了，一直没同意，想请教一下问题。
